CREATE TABLE top_stock_screens (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL COLLATE NOCASE UNIQUE,
    url TEXT NOT NULL,
    max_stock_count INTEGER NOT NULL DEFAULT 100
        CHECK (max_stock_count BETWEEN 1 AND 500),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
